### ISSUE TITLE
Changes required to support Access

### ISSUE THREAD

**Issue by maxwellpower** [acuparse/acuparse#17]
So after receiving my access and taking a look at the data, Acuparse should be able to parse data from the Access with some modifications:
1. The Access sends it's data to https://atlasapi.myacurite.com. This, of course, is a secure site. Lucky the Access does not require strict certificate checking and so we are able to present any cert to the Access. At some point, Acurite could make things difficult by enabling strict cert checking on the Access. This would prevent Acuparse from intercepting without some major intervention. My guess is that will create more firmware issues/overhead than anything and so it will hopefully remain unimplemented.
2. The Access now makes a POST request instead of a GET request. Update data is still sent as GET parameters in the URL. MyAcuRite returns an empty variable upon success `{}`?
3. 5n1 readings appear to be combined instead of sending two separate readings from the sensor groups. It seems like it might send data at the same rate, just with all values included each time, updating the ones that changed. Need some more data on this to be sure.
4. Updates are sent every 5 minutes and not in real-time.

There are some minor changes to the readings that are provided by the Access. Here are strings for a 5n1 and a Tower:

5n1:
`POST /weatherstation/updateweatherstation?&dateutc=2018-01-28T02:45:01&id={MAC}&mt=5N1&sensor=00000000&sensorbattery=normal&rssi=4&hubbattery=low&baromin=28.04&humidity=87&tempf=2.7&windspeedmph=2&winddir=45&windgustmph=2&windgustdir=45&windspeedavgmph=1&heatindex=2.7&feelslike=-3.6&windchill=2.7&dewptf=-0.3&dailyrainin=0.00&rainin=0.00`

Tower:
`POST /weatherstation/updateweatherstation?&dateutc=2018-01-28T02:45:01&id={MAC}&mt=tower&sensor=00000000&sensorbattery=normal&rssi=4&hubbattery=low&baromin=28.04&humidity=1&tempf=92.1&dewptf=-21.7`

**Comment by nincehelser** [comment]
It's interesting that they're sending windgust and windgustdir values to myAcurite since myAcurite won't display gust data.  They're sending it to wunderground, too, but I've never seen wunderground plot gust direction.

**Comment by nincehelser** [comment]
windspeedavgmph is new, too, but now the question is what is myAcurite actually plotting for wind?

**Comment by maxwellpower** [comment]
The new parameters on the 5n1 appear to be: `windgustmph, windgustdir, windspeedavgmph, heatindex, feelslike, windchill`.

It's interesting. I don't know why they would have included them either. Since the 5n1 isn't capable of providing gust readings. It measures wind every 38 seconds. It seems like a waste to also include those since, at the moment, the readings appear to be the same as the normal wind readings. I think I will ignore them for now since Acuparse has no need for them currently. When support for the Atlas sensors is actually required, I'll update the DB to store those readings. Database updates could be destructive to some users and so I'll save that for later; it will also require more testing.

The Heat Index, Feels Like, and Windchill is also interesting. Since Acuparse calculates these values manually at the moment. I think including them in an update would also be pointless. Once the Atlas comes online, it will be worth implementing the changes to include this data. For now, to support both the smartHUB and Access, I'll ignore those readings too. I believe the idea at the moment will be for version 3 to support the Access/Atlas/Towers only and version 2 will remain locked to the 5n1. Not totally decided yet.

Adding the time and date is also helpful for the Access. I believe you're correct, this should allow it to save the readings and replay them once power/inet is restored. Watching the Access come online, it made a request to my NTP server. It must now be keeping its own time. Since the smartHUB does not, it relies on the timestamp returned on data submission. The stamp Acurite sent was always wrong but the only thing it was really used for was clearing rainfall data.

Once I get the data flowing out of the Access in a usable way, I'll be able to test the backup and how it dumps out that data. Right now, it seems like it will just replay the data, all the way to the live data.

So overall, I'm not totally sure what Acurite was thinking here with the Access. It seems like a nice enough device but if the problem they were having was network overload, this is only going to make it much worse. Since they are sending more parameters over TLS for no apparent reason. Surely the TLS overhead it's self must be huge on myacurite servers. They could have left the TLS/SSL out of this. None of the data is sensitive enough to warrant protection from interception, IMO. It just creates an additional layer of complexity. Either way, the overhead for Acuparse should not be an issue. Since it's only accepting readings from a single source. I also have no idea why they moved to a POST request instead of a GET. Sure POST is slightly more private/secure, but who cares? It's weather data.

Also worth noting, when sending updates to myacurite, it now requires a proper "User-Agent" when submitting data. Their API is actually nice enough to report what it wants. So in this case, we set the user agent to `Atlas/046`. Which is what the Access is currently sending out.

**Comment by nincehelser** [comment]
Wind speed from the 5n1 updates every 18 seconds.  There are two data packets that alternate from the 5n1 sensor, and windspeed is in both.

Some of those parameters are also being sent to wunderground, at least with the Atlas.  Wunderground just seems to ignore them, though.  It's also odd that they are sending things like feelslike and windchill that were calculated on the server side in the past.  Perhaps we're seeing something that may indicate more useful data being available directly from the Access in a local API?  They've definitely got plans for this thing...

As for the encryption, Acurite was having an issue with some ISPs messing with the data in the name of "web acceleration".  In reality they were trying to conserve bandwidth on expensive satellite links.  Encrypting the data hides it from those ISPs and avoids the problems their "web acceleration" was causing.

I'm sure there are other reasons, too, like some users just wanting everything encrypted in the name of security.  It seems a waste to me, too, and it certainly makes things harder to debug.  Oh, well...

**Comment by maxwellpower** [comment]
You're totally right. It's been a while since I played with any of the raw data.
Speed is sent every 18 seconds while the direction is sent every 38. Neither are good enough for gust. If I remember correctly, gust should be calculated using readings every 2-4 seconds. This is IMO the core reason for upgrading to the Atlas line. I experience a lot of wind gust here.

It does make me wonder if they are going to enable some form of API locally on the Access. It seems to be the only reason you would calculate those values locally. Otherwise, it just takes resources that are better spent on the server side. Other than having the Access display the live data on its local server, I don't know how useful an API would be. Would the data be limited? If anything, I would suspect any API would be better provided through the myacurite service and not the Access directly. Having to poll my Access to get data would be much more painful as compared to sending it out as it happens. If you want to use an IFTTT, it will most likely need to interface with the myacurite service anyway, since firewalls/NAT ...

Preventing acceleration and modification would be a strong argument for the use of TLS on the connection. Something I personally have not thought about until now. If this is the primary reason, I suspect there would definitely not be any reason to enable strict certificate checking on the Access side. Since the only need for a cert is to encrypt the packet and not to prevent eavesdropping. It's useless from a security perspective; only because we're talking about weather data and not nuclear launch codes. I'm sure there are some that could make an argument for why their weather data is somehow special, but it's not. If it's really that special, you're probably not buying an Acurite station.

Based on what I know about the Access at the moment, Acurite does seem to be moving in the right direction. As long as strict checking remains unimplemented overall, I'll be a happy camper and a proud owner of an Atlas Elite.
