### ISSUE TITLE
Does Access integration mean data doesn’t get uploaded to Acurite?

### ISSUE THREAD

**Issue by bdwilson** [acuparse/acuparse#26]
Curious if your dns interception of the Access API host means that data isn’t delivered to their servers. I’d like to still use their app, but also keep data local. Is this possible? 

Thanks for your work on this!

**Comment by maxwellpower** [comment]
The DNS redirect sends updates to your Acuparse server. Acuparse takes the update and rips the data, then sends the update off to MyAcuRite. Same as if your hub/access uploaded it directly. You can enable/disable the uploading of data in the same way as WU, PWS, or CWOP in the config. By default, Acuparse will send the update data to MyAcuRite.

**Comment by bdwilson** [comment]
Awesome!  Looking for alternatives before the EOL date. Appreciate your work on this!
