### ISSUE TITLE
Can tower sensor data be used for dew point calculation on upload?

### ISSUE THREAD

**Issue by Katjubu** [acuparse/acuparse#41]
I added a tower sensor because the temperature on my 5in1 consistently reads high. After changing the default upload sensor to the tower, Acuparse is still uploading the dew point to WU based on the incorrect 5in1 data. Is there any way to change this behaviour based on the "Master Temp/Humidity Sensor" setting? Thank you.

**Comment by maxwellpower** [comment]
Is definitely an issue and will be updated asap.
