### ISSUE TITLE
How to access the "Export JSON data for use in external applications" feature?

### ISSUE THREAD

**Issue by pvince** [acuparse/acuparse#44]
I have acuparse setup and functioning, I was looking into ways I could access the data and noticed the feature bullet point:
* Export JSON data for use in external applications.

I looked over the documentation & code and I can't seem to figure out how to access the JSON export.

**Comment by maxwellpower** [comment]
Hello,

Is in the Install Guide, under the heading Data Display.
`docs/INSTALL.md` 
[https://acuparse.github.io/acuparse/INSTALL](https://acuparse.github.io/acuparse/INSTALL)

Long story short, add "?json" to the end of your URL.

For example. https://www.ghwx.ca/?json
