### ISSUE TITLE
edit the database

### ISSUE THREAD

**Issue by csmithsound** [acuparse/acuparse#60]
On initial set up the temperature was recorded at -17C when actual temperature was 4C. After a few seconds the temperature corrected. 

Is there anyway i can edit the database to remove these first few readings? 

<img width="615" alt="screen shot 2019-03-07 at 15 55 56" src="https://user-images.githubusercontent.com/48320621/53970509-c7cee880-40f2-11e9-8aed-f12629d2be47.png">

**Comment by maxwellpower** [comment]
This should do it:
`mysql -u<USERNAME> -p<PASSWORD> -e "DELETE FROM acuparse.archive WHERE tempC = -17"`

**Comment by csmithsound** [comment]
great thanks, i actualy realised i could juse re create the database.

**Comment by csmithsound** [comment]
-17.8 came back after deleting and recreating. This time it wasn't there initially. 

pi@raspberrypi:~ $ sudo mysql -uroot -pchr1st0ph3r -e "DELETE FROM acuparse.archive WHERE tempC = -17.8”
> 

that command 
doesn't seem to work.

**Comment by mfrazzz** [comment]
Do you get an error or status back after the command runs?

**Comment by maxwellpower** [comment]
Since -17.8C is a rounded 0F try running:
`mysql -uroot -p<PASSWORD> -e "DELETE FROM acuparse.archive WHERE tempF = 0"`

tempF is the reading received from the sensors.

**Comment by csmithsound** [comment]
after the comand i get '>' 

pi@raspberrypi:~ $ sudo mysql -uroot -pmypassword -e "DELETE FROM acuparse.archive WHERE tempC = -17.8”
>

**Comment by csmithsound** [comment]
ok so i found out that means the command is still running but i left it all day and it didn't complete. 
How long should this take? 
can i just delete the timeframe instead? 
Low: -17.8℃ (0℉) on 7 Mar @ 17:24

**Comment by maxwellpower** [comment]
Try
`mysql -uroot -p<PASSWORD> -e "DELETE FROM acuparse.archive WHERE tempF = 0;"`

**Comment by GaryKOHOHIO2** [comment]
csmith, I THINK you need a semi-colon at the end of sql commands. I'm inexperienced, but I frequently forget that.

**Comment by csmithsound** [comment]
this one worked. ;-)


sudo mysql -uroot -pchr1st0ph3r -e "DELETE FROM acuparse.archive WHERE tempF = 0";
