### ISSUE TITLE
Windy.com API support request

### ISSUE THREAD

**Issue by gus70** [acuparse/acuparse#71]
This is a request to add Windy.com upload capability using their new API.
https://community.windy.com/topic/8168/report-you-weather-station-data-to-windy

Thanks.

**Comment by mfrazzz** [comment]
According to the comments, if you are sending to CWOP, Windy is already injesting your data via MADIS.

**Comment by gus70** [comment]
Yes but it isn't the same thing. There are advantages of sending directly to Windy. Your data on Windy via CWOP that comes from MADIS is delayed an average of 10 minutes and up to 19 minutes at times. When sending directly to Windy you data is never more than 5 minutes delayed. Also only when you send directly does your station show forecast precipitation with the forecasting models. Besides it sounds like Windy is developing even more features for their future API versions. 

See here for details and comparison.
https://community.windy.com/topic/8263/windy-station-vs-cwop-station

**Comment by maxwellpower** [comment]
I think this should be easy enough to implement either way. I think there is going to be a market shift over time away from WU as they continue to lock down their API. I believe it's best to support as many 3rd party providers as possible.
